site_name: Oscovida Documentation
site_description: TODO
site_url: https://oscovida.github.io

theme:
  name: material
  palette:
    language: en

repo_name: oscovida/oscovida
repo_url: https://github.com/oscovida/oscovida
edit_uri: ""

nav:
  - Quick-Start: './quick-start.ipynb'
  - Examples:
    - 'Germany': './examples/germany.ipynb'
  - API Documentation:
    - 'Regions': './api/regions.md'
    - 'Statistics': './api/statistics.md'
    - 'Plotting': './api/plotting.md'
  - Contributing: './contributing.md'

plugins:
  - search
  - mkdocstrings
  - mknotebooks:
        binder: true
        binder_service_name: "gh"
        binder_branch: "master"

extra_css:
  - css/mkdocstrings.css

markdown_extensions:
  - tables
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - codehilite
